# Generated by Django 6.1 on 2026-08-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
